version: '3.8'

services:
  telegram_bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached

  nginx:
    image: nginx:latest
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
