"""Create orders table

Revision ID: 6d0d90983f8d
Revises: 5d4300692833
Create Date: 2025-03-30 00:09:12.156235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d0d90983f8d'
down_revision: Union[str, None] = '5d4300692833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('door_type', sa.String(), nullable=False),
    sa.Column('priorities', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('user_request', sa.String(), nullable=True),
    sa.Column('gpt_answer', sa.String(), nullable=True),
    sa.Column('call_measurer', sa.Boolean(), nullable=True),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
