"""jokes

Revision ID: 8f22342b65db
Revises: 6d0d90983f8d
Create Date: 2025-03-30 00:12:13.026191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f22342b65db'
down_revision: Union[str, None] = '6d0d90983f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anecdotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anecdotes_id'), 'anecdotes', ['id'], unique=False)
    op.create_table('jokes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jokes_id'), 'jokes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jokes_id'), table_name='jokes')
    op.drop_table('jokes')
    op.drop_index(op.f('ix_anecdotes_id'), table_name='anecdotes')
    op.drop_table('anecdotes')
    # ### end Alembic commands ###
