"""jokes

Revision ID: 92b630ca458e
Revises: 8f22342b65db
Create Date: 2025-03-30 00:24:34.700726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b630ca458e'
down_revision: Union[str, None] = '8f22342b65db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anecdotes', sa.Column('text', sa.Text(), nullable=False))
    op.drop_column('anecdotes', 'message')
    op.add_column('jokes', sa.Column('text', sa.Text(), nullable=False))
    op.drop_column('jokes', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jokes', sa.Column('message', sa.TEXT(), nullable=False))
    op.drop_column('jokes', 'text')
    op.add_column('anecdotes', sa.Column('message', sa.TEXT(), nullable=False))
    op.drop_column('anecdotes', 'text')
    # ### end Alembic commands ###
